name: vitacheck
description: A health based app with a hardware device to monitor body vital and book appointment with patient favourate .
publish_to: 'none' 

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  equatable: ^2.0.5
  validators: ^3.0.0
  outlined_text: ^1.0.1
  shared_preferences: ^2.0.13
  animated_splash_screen: ^1.3.0
  toast: ^0.3.0
  dependencies:
  calendar_date_picker2: ^0.3.7
  dio: ^4.0.6
  
  fl_animated_linechart: ^1.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/
